// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Soundboard.Domain.DataAccess;

#nullable disable

namespace Soundboard.Domain.DataAccess.Migrations
{
    [DbContext(typeof(SoundboardDbContext))]
    [Migration("20250830220215_AddHotkeyFieldsOnLoad")]
    partial class AddHotkeyFieldsOnLoad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Soundboard.Domain.DataAccess.Implementations.SoundButton", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BoundKeyCode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BoundKeyModifiers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("GridId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HotKey")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.HasIndex("GridId");

                    b.ToTable("SoundButtons");
                });

            modelBuilder.Entity("Soundboard.Domain.DataAccess.Implementations.SoundButtonGridLayout", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(127)
                        .HasColumnType("TEXT");

                    b.HasKey("Guid");

                    b.ToTable("GridLayouts");
                });

            modelBuilder.Entity("Soundboard.Domain.DataAccess.Implementations.SoundButton", b =>
                {
                    b.HasOne("Soundboard.Domain.DataAccess.Implementations.SoundButtonGridLayout", "GridLayout")
                        .WithMany("SoundButtons")
                        .HasForeignKey("GridId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GridLayout");
                });

            modelBuilder.Entity("Soundboard.Domain.DataAccess.Implementations.SoundButtonGridLayout", b =>
                {
                    b.Navigation("SoundButtons");
                });
#pragma warning restore 612, 618
        }
    }
}
